/tigress/ruairidh/model_results
--arch=vgg\ --resume=False
vgg_15_BN_64.out
entering python script
Traceback (most recent call last):
  File "../main.py", line 444, in <module>
    main()
  File "../main.py", line 330, in main
    config = parse_args()
  File "../main.py", line 163, in parse_args
    config = get_config(args)
  File "/home/ruairidh/superman/cifar10-human-experiments/pytorch_image_classification/argparser.py", line 309, in get_config
    args = _set_default_values(args)
  File "/home/ruairidh/superman/cifar10-human-experiments/pytorch_image_classification/argparser.py", line 285, in _set_default_values
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/vgg\\.json'
done
