/tigress/ruairidh/model_results
--arch=wrn --depth 28 --widening_factor 10 --use_cutout --cutout_size 16
wrn_28_10.out
entering python script
[2018/11/12 02:52:58 __main__ INFO] - {
  "model_config": {
    "arch": "wrn",
    "input_shape": [
      1,
      3,
      32,
      32
    ],
    "n_classes": 10,
    "base_channels": 16,
    "depth": 28,
    "widening_factor": 10,
    "drop_rate": 0
  },
  "optim_config": {
    "epochs": 200,
    "batch_size": 128,
    "optimizer": "sgd",
    "base_lr": 0.1,
    "weight_decay": 0.0005,
    "momentum": 0.9,
    "nesterov": true,
    "scheduler": "multistep",
    "milestones": [
      60,
      120,
      160
    ],
    "lr_decay": 0.2
  },
  "data_config": {
    "dataset": "CIFAR10",
    "n_classes": 10,
    "num_workers": 7,
    "batch_size": 128,
    "use_cutout": true,
    "cutout_size": 16,
    "cutout_prob": 1,
    "cutout_inside": false,
    "use_random_erasing": false,
    "use_mixup": false,
    "c10h_sample": false,
    "c10h_testsplit_percent": 0.1,
    "c10h_datasplit_seed": 999,
    "use_gpu": true
  },
  "run_config": {
    "outdir": "/tigress/ruairidh/model_results/wrn_28_10",
    "seed": 7,
    "test_first": true,
    "gpu": "0",
    "tensorboard": false,
    "tensorboard_train_images": false,
    "tensorboard_test_images": false,
    "tensorboard_model_params": false,
    "human_tune": false,
    "no_output": false,
    "test_only": false,
    "nonhuman_control": false,
    "c10h_scores_outdir": "tmp",
    "c10h_save_interval": 1,
    "use_gpu": true
  },
  "env_info": {
    "pytorch_version": "0.4.1",
    "cuda_version": "9.0.176",
    "cudnn_version": 7102,
    "gpu0": {
      "name": "Tesla P100-PCIE-16GB",
      "capability": "6.0"
    }
  }
}
outdir:  /tigress/ruairidh/model_results/wrn_28_10
Traceback (most recent call last):
  File "../main.py", line 445, in <module>
    main()
  File "../main.py", line 358, in main
    json.dump(config, fout, indent=2)
OSError: [Errno 122] Disk quota exceeded
cp: failed to close ‘/tigress/ruairidh/model_results/./wrn_28_10.out’: Disk quota exceeded
done
