entering python script
[2018/09/21 15:12:02 __main__ INFO] - {
  "model_config": {
    "arch": "vgg",
    "input_shape": [
      1,
      3,
      32,
      32
    ],
    "n_classes": 10,
    "n_channels": [
      64,
      128,
      256,
      512,
      512
    ],
    "n_layers": [
      2,
      2,
      3,
      3,
      3
    ],
    "use_bn": true
  },
  "optim_config": {
    "epochs": 160,
    "batch_size": 128,
    "optimizer": "sgd",
    "base_lr": 0.1,
    "weight_decay": 0.0001,
    "momentum": 0.9,
    "nesterov": true,
    "scheduler": "multistep",
    "milestones": [
      80,
      120
    ],
    "lr_decay": 0.1
  },
  "data_config": {
    "dataset": "CIFAR10",
    "n_classes": 10,
    "num_workers": 7,
    "batch_size": 128,
    "use_cutout": false,
    "use_random_erasing": false,
    "use_mixup": false,
    "use_gpu": true
  },
  "run_config": {
    "outdir": "/tigress/ruairidh/iclr/model_results/vgg_15_BN_64/",
    "seed": 7,
    "test_first": true,
    "gpu": "0",
    "tensorboard": false,
    "tensorboard_train_images": false,
    "tensorboard_test_images": false,
    "tensorboard_model_params": false,
    "use_gpu": true
  },
  "env_info": {
    "pytorch_version": "0.4.1",
    "cuda_version": "9.2.148",
    "cudnn_version": 7104,
    "gpu0": {
      "name": "Tesla P100-PCIE-16GB",
      "capability": "6.0"
    }
  }
}
Files already downloaded and verified
Files already downloaded and verified
[2018/09/21 15:12:03 __main__ INFO] - Loading model...
[2018/09/21 15:12:04 __main__ INFO] - n_params: 14728266
[2018/09/21 15:12:06 __main__ INFO] - Done
/home/ruairidh/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
[2018/09/21 15:12:06 __main__ INFO] - Test 0
[2018/09/21 15:12:09 __main__ INFO] - Epoch 0 Loss 2.3026 Accuracy 0.1001
[2018/09/21 15:12:09 __main__ INFO] - Elapsed 3.05
[2018/09/21 15:12:09 __main__ INFO] - Train 1
[2018/09/21 15:12:10 __main__ INFO] - Epoch 1 Step 0/390 Loss 2.3366 (2.3366) Accuracy 0.1172 (0.1172)
[2018/09/21 15:12:14 __main__ INFO] - Epoch 1 Step 100/390 Loss 1.8497 (2.1780) Accuracy 0.2266 (0.2158)
[2018/09/21 15:12:18 __main__ INFO] - Epoch 1 Step 200/390 Loss 1.6145 (1.9583) Accuracy 0.3203 (0.2693)
[2018/09/21 15:12:23 __main__ INFO] - Epoch 1 Step 300/390 Loss 1.4937 (1.8369) Accuracy 0.3906 (0.3120)
[2018/09/21 15:12:26 __main__ INFO] - Elapsed 17.61
[2018/09/21 15:12:26 __main__ INFO] - Test 1
[2018/09/21 15:12:29 __main__ INFO] - Epoch 1 Loss 1.4502 Accuracy 0.4603
[2018/09/21 15:12:29 __main__ INFO] - Elapsed 2.75
Traceback (most recent call last):
  File "./main.py", line 393, in <module>
    main()
  File "./main.py", line 384, in main
    save_checkpoint(state, outdir)
TypeError: save_checkpoint() missing 1 required positional argument: 'outdir'
done
